//Used by Avatar
#define PIXMAP_DIMENSION 72  //58 
#define PIXMAP_STORED_DIMENSION 128
#define SHADOW_OFFSET_X 5 
#define SHADOW_OFFSET_Y 4 
#define SHADOW_OPACITY 192 
#define SHADOW_MARGIN 0
#define NAME_OFFSET 5 
#define NAME_MARGIN 3 
#define NAME_OPACITY 200
#define NAME_OUTLINE_WIDTH 3
#define ICON_OPACITY 255 
#define FONT_SIZE 9

#define ANIM_MOVE_DURATION 599
#define ANIM_OPEN_DURATION 575 
#define ANIM_CLOSE_DURATION 250 
#define ANIM_HIGHLIGHT_DURATION 750 

